#include <iostream>
#include <bits/stdc++.h>
using namespace std;

int f(int x) // function definition generates the even set of numbers
{
    // base case
    if (x == 0)
        return x;
    else
        return (f(x - 1) + 2); // recurse
}

int main()
{
    /*
    Q2.
 Write and test a recursive function that returns the value of the following recursive definition:

f ( x ) = 0 if x  0
f ( x ) = f ( x -1) + 2 otherwise

What set of numbers is generated by this definition?
*/
    cout << "Input a number ";
    int n;
    cin >> n;
    

    // prints f(n) i.e nth term
    // cout << "f(" << n << ")"
    //      << " = " << f(n) << " , if x = " << n << endl;



    // printing f(n) till n
     for (int i = 0; i < n; i++)
     {
         cout <<"f("<<i<<")"<<" = " <<f(i)<<"   , if x = "<<i<<endl; //prints f(i) i.e ith term
     }

    return 0;
}
